README.md, app.js, config/secrets.js, controllers/api.js, package.json, views/api/index.jade, views/api/lob.jade
I've been seeing lob at a lot of hackathons recently, so I decided to add an API example for it.
=> Added Lob Api example

README.md
the generator warning is duplicated
=> remove duplicate note

README.md
`git remote rm origin` needs to be run inside the project directory.
=> Put change directory before removing git remote in README

README.md
I thought it would be better to let know the user where they should paste the file for views and how to make routing work.
=> clear up the path for view files.

controllers/api.js
=> User model doesn't seem to be used in this file

models/User.js
5 rounds is way too low for 2015, better increase it to at least 10.
=> Update bcrypt rounds

README.md
Changing yum to dnf since yum is deprecated in the current version of Fedora.
=> Adapting installation commands of the prerequisites in Fedora Linux.

README.md
=> git clone should be not have --bare flag.

README.md
mainly changed web site to web apps as that was a change in the azure UI from request #294
=> minor updates to the deployment steps for azure

README.md
Before converting any file from HTML To Jade, we remember to update all the CSS and JS paths.
=> Some minor modification request on README.md

views/account/login.jade, views/account/profile.jade
I felt that the page "jumped around" when navigating between the login, profile and account, so I aligned all of the fields in the forms on the different pages.
=> align the styling on /login, /profile and /account

app.js, config/passport.js, config/secrets.js, models/User.js, package.json, views/account/login.jade
Also populate some profile data using request and the steam web api.
=> Added steam authentication using passport-openid

test/models.js
=> Add semicolon to test/model.js

controllers/user.js
'next' is undefined for getReset call in user controller. This PR fixes it.
=> Fix next being undefined for getReset call

controllers/api.js
Added missing return on error.
=> Fixes #413 Can't set headers after they are sent

package.json
Remove connect-assets requirement from package.json
=> Remove connect-assets from package.json

views/account/profile.jade
[Not everyone is male or female.](https://en.wikipedia.org/wiki/Genderqueer) This commit adds an "Other" choice on the profile page.
=> Add "Other" gender choice on profile page

controllers/api.js
=> replace broken show function in GitHub API example

views/layout.jade
New Pull request without the compiled css.
=> Added <meta theme-color> into layout.jade

controllers/api.js
=> support reserved let in node v5.11.0

README.md
SendGrid has updated their logo.
=> Update SendGrid Logo

README.md
=> Add Google App Engine Flexible Environment deployment instructions.

package.json
Related to https://github.com/sahat/hackathon-starter/issues/546
=> A few dependency upgrades

views/account/profile.pug
Pug 0.1.0 (Jade 2.x) removed support for interpolation in attributes.
https://github.com/pugjs/pug/issues/2305
=> GET profile page input value issue

config/passport.js, controllers/api.js, controllers/user.js
My linter noticed some missing error checks in callbacks. Catching these will prevent uncaught exceptions or unexpected application states in edge cases.
=> Add missing error guards

README.md
=> Add testimonials

README.md
Adds cheatsheets from MegaBoilerPlate (relevant to this project also).
=> Adds more cheatsheets to Readme

views/partials/footer.pug
change copyright year from 2016 to 2017 in views/partials/footer.pug
=> change year from 2016 to 2017

controllers/api.js
With user I have an error: `Bad Request Empty value for parameter 'owner': undefined`
It work great with owner :)
=> fix owner is undefined

.dockerignore, Dockerfile, README.md, docker-compose.yml
Creating pull request to highlight changes made to repo. Reaching out to @sahat shortly.
- Added docker
- Docker-compose
- MongoDB (docker)
=> Adding docker compose

README.md
Added spacing to properly markdown Mongoose Cheatsheet. Also added missing closing brace from Promises .then() example.
=> fixed markdown issue and promises .then() issue

README.md
###Heading 3 will not render properly in Github Markdown anymore -- needs a space, i.e.
=> Fix minor formatting issue in README.md

Dockerfile
* Smaller - Use `node:6-slim` image
* Faster - Add `NODE_ENV` for node
* Faster - Use `yarn` (Pre-installed with official docker images)
* Faster & Smaller - Install `dependencies` packages only
=> Optimize Dockerfile for production env

README.md
Space missing in markdown syntax.
=> Minor Typo Correction

controllers/user.js
As per https://github.com/chriso/validator.js#sanitizers there is no option key remove_dots, it changed to gmail_remove_dots .
=> normalizeEmail options key remove_dots changed to gmail_remove_dots

README.md
@sahat See latest pull request for updating Bluemix content with the most updated steps to get started on using Bluemix and Watson services.
=> Bluemix Content Update 

app.js, views/api/bitgo.pug, views/api/steam.pug, views/partials/header.pug
As title. We'd better use type-safe operators instead.
=> use type-safe equality operator instead

README.md
Changed package-lock.lock to package-lock.json inside README.md file
=> changes done in README.md file for the name of package-lock.json

views/partials/footer.pug
=> Updated footer from 2017 to 2018

README.md
Made it just a _little_ less difficult to get started with Facebook.
=> Update Facebook instructions 

LICENSE
=> update date in LICENSE

config/passport.js, controllers/api.js, controllers/contact.js, controllers/user.js, public/js/main.js
With recent versions of nodeJS, it is possible to use the template litteral and destructuring assignment. I also used eslint to correct possible syntax errors.
Link with #720
=> use new es6 syntax

README.md
Information about some files and libraries is missing in the readme.
=> add new files and update list package in readme.md

views/api/instagram.pug
For the instagram page the images are not displayed. HTML display '#{user.profile_picture}' instead of value.
=> Fix bug display image in view instagram

README.md, controllers/api.js, controllers/user.js, package.json
bluebird is useless with nodejs 8 because promises are used natively.
=> Remove bluebird

controllers/api.js, views/api/lastfm.pug
I refactorized the code with the es6 syntax. I also took the opportunity to make the variable names clearer for developers and handle the case where information is missing.
In-part from #814
=> Refactor last.fm api with es6 syntax and async/await

controllers/api.js
[Twit](https://github.com/ttezel/twit) library natively supports promise. It is better to use the new syntax es6. This eliminates the need for callback.
=> refactor twitter api with es6 syntax and async/await

controllers/api.js
github library ([@octokit/rest](https://github.com/octokit/rest.js)) natively supports promise.
=> refactor github api with es6 syntax and async/await

controllers/api.js, views/api/steam.pug
Partial reformatting of the getSteam function with ES6 syntax. Fixed a bug that could happen if you had no game. Also, I have the impression that the api steam has recently changed but I haven't done any more research on it.
=> reformat partially getSteam with es6 syntax

controllers/api.js
Calling only the function that is used allows more clarity and lightness.
Replace `const util = require('util');`by `const { promisify } = require('util');`
=> call only promisify on util

controllers/api.js, package-lock.json
Do I need to add a test for this? If so, where at? There are currently only tests for the app and the models.
=> destructuring statuses from an extra layer deep to fix bug in view

controllers/api.js
Until new API keys and a a phone number is provided this will render a 401 in the browser.
=> Twilio api update

.dockerignore
Fixes #869.
Copies the assets/libs to the docker container.
=> fix: copy libs to public/lib folder

public/css/themes/modern/_modern.scss, public/css/themes/modern/_variables.scss
=> update the modern theme to be consistent with bootstrap

README.md
Fixes #915
Hey, 
Since mLab is being acquired by MongoDB, Inc.  I have made some changes in documentation for mLab.
Do you want any more changes?
Thanks
=> Update documentation for use of MongoDB Atlas

views/account/login.pug
Fix for issue #931 where login / sign in buttons are out of alignment at a certain width (approx 730px).
=> Fixed Allignment Issue for login / sign in buttons

config/passport.js
`profile._json.email` references the **public** email address of a Github user.
By requesting the `user:email` scope on auth, we can retrieve & iterate over the **private** email addresses on a profile.
`profile.emails` looks like this:
```
[
{ value: 'my@email.com',             primary: false, verified: true },
{ value: 'another@email-domain.com', primary: true,  verified: true },
{ value: 'nospam@spam.com',          primary: false, verified: true }
]
```
See here for info: https://stackoverflow.com/a/37429696
=> Iterate through Github private email addresses on register/login of new user

.env.example, app.js, controllers/api.js, package-lock.json, package.json, views/api/chart.pug, views/api/index.pug, views/layout.pug
This PR is to add an example of chart.js using an API to get closing stock values from Microsoft for the last 7 days
=> Add Charts Example

README.md, prod-checklist.md
This document is to outline some of the suggested changed after the hackathon project is done to help the developers to get their code more production ready
=> Add prod-checklist.md

README.md
Site is no longer available and domain is up for sale.
=> Removed unavailable UIBOX link

test/models.js
https://github.com/sahat/hackathon-starter/issues/882
=> Unit test user model

test/app.js
=> add GET /forgot test

controllers/api.js
Fix by adding Client-ID in the header
=> fix: twitch api integration

controllers/user.js
Created a new helper function to abstract sendMail functionality.
=> Refactored sendMail transporter calls #1102

.env.example, README.md, controllers/contact.js, controllers/user.js, package-lock.json, package.json
https://github.com/sahat/hackathon-starter/issues/1110
=> Add support for SendGrid API

Dockerfile
update to pm2 process manager.
=> update to  process manager

README.md
Removed dot to keep consistency in the documentation. #hackathon
=> Removed dot to keep consistency in the documentation

README.md
Added the word "know" as it was missing before "...the new process".
=> Update Readme.  Fixes #1140

models/User.js, package-lock.json, package.json
@node-rs/bcrypt is faster and easier to install, see: https://github.com/napi-rs/node-rs/tree/main/packages/bcrypt
=> Use faster bcrypt implementation

config/passport.js
This PR is linked to Issue #1132
=> Updating GitHub strategy: Check for null email value

app.js
Added 4th argument so express identifies the function as an error-handler.
=> Updated error handler

README.md, config/passport.js, controllers/user.js, package-lock.json, package.json
Many functionalities previously offered by lodash are now available natively or can be implemented easily using current Node.js features. This change reduces project dependencies.
=> chore: remove lodash dependency

app.js, config/passport.js, controllers/api.js, controllers/user.js, test/models.js, test/nodemailer.js, views/account/login.pug, views/api/google-drive.pug, views/api/google-sheets.pug
- Prevent OAuth redirect loops by implementing safe returnTo paths and better handling for duplicate accounts
- Standardize email normalization across OAuth and manual signup
- Fix Twitch OAuth email extraction
- Implement secure account discovery flow with email notifications and mitigate user enumeration vulnerabilities in signup/password flows
- Reduce OAuth permissions requested from Google
- Fix crash if insufficient permissions for Google API examples were granted
- Reject disposable emails during signup and profile updates
- Additional unit tests
=> fix(auth): enhance OAuth flow and improve account security

config/passport.js
Changed "senarious" -> "scenarios"
=> Fixed a small typo in config/passport.js
