sahat/hackathon-starter

public/css/themes/flatly/_styles.scss, public/css/themes/flatly/_variables.scss
Current version was using variables before they had been declared, and the box-shadow function needed to be included in order to work
=> Updating Flatly theme to 3.3.2

views/account/profile.jade
When viewing /account in a window less than 768px, the radio buttons are positioned off the page:
Adding the bootstap column class used on other form fields on the page to the radio buttons moves them onto the page and in line with the rest of the form..
=> Fix radio button alignment on small screens

public/css/themes/modern.less
This small PR adds declaration for links `:focus` state in order to remove issue with links having the same color as background in the `modern` theme.
Thanks!
=> Add focus state declaration to footer links. Closes #258

README.md
I updated the README to show packages that are actually in the `package.json` (paypal-rest-sdk, multer, serve-favicon, ordrin-api) (see https://github.com/saveman71/hackathon-starter/commit/d55bb05347b481b37ee4dc78fd841844a85c4b25 for a better diff).
I also improved lisibility by removing center align on tables (let me know if you don't want that) and adding spaces in the markdown (http://wbond.net/sublime_packages/alignment ftw).
Cheers
=> Added missing package in README

README.md, config/secrets.js
Updates to the docs for Heroku one-click deploy per #294.
`heroku addons:add` was deprecated and replaced by `heroku addons:create`
I also updated `secrets.js` to automatically pick up the `MONGOLAB_URI` environment var set by the Mongolab add-on in the Heroku environment to make deployment dead-simple.
=> Updates for one-step-deployment to Heroku

controllers/api.js
need to update stripe create charge method.  param SOURCE instead of CARD should be used to create a Stripe Charge https://stripe.com/docs/api#create_charge
=> stripe POST to api/stripe uses 'source' not 'card' in the stripe.charges.create method

views/partials/flash.jade
the flash error message used `span.ion-close-circled` for the close circle. Other message already used the font-awesome version `i.fa.fa-times-circle-o`.
=> swap ion icon with font-awesome in partials

README.md
According to changelog the multer package is no longer included.
=> Remove multer from README.md list of packages

config/secrets.js, controllers/api.js
This fix is required for integrating with the new Facebook Graph API version 2.5 or above.
- added the profile fields in /me request for most recent Facebook Graph API
=> Missing public profile and email after switching to another Facebook App ID and Secret #348

public/css/main.scss
removed horizontal `textarea` resizing as not to break responsiveness when adjusted.
=> disabled horizontal resizing of textarea

controllers/user.js
Just my two cents. It's fairly common to have dots in the user's email address and it will appear to the user that they have not signed up since the email is normalized. My pull request allows for dots in the user's email but still removes plus. I can understand removing the plus since that can be "spammy".
=> Dots should be allowed in email.

controllers/api.js
Copied latest YQL example from https://developer.yahoo.com/weather/
It's still the same location as the current query (Nome, AK).
I tested it, and this resolves #437
=> Fix Yahoo Weather API example

app.js
Instead of checking for explicit routes, this tries to exclude any unwanted routes and store anything else. All of the following 5 conditions have to be met in order to save the current path
1. User must not be logged in (saves some resources)
2. Route must not be `/login` (you don't want to get back to login after login)
3. Route must not be `/signup` (same reason as above)
4. Route must not start with `/auth` (same reason as above)
5. Path does not contain a dot (this usually matches a file and you don't want to be redirected to `favicon.ico`)
=> improve redirect after login

README.md
Fixed cloning instructions in README.md
Users can now easily clone the ES5 variation of the starter pack.
=> Added easy clone support for ES5 variation

README.md
I've updated the READ to reflect the changes I see from the code and what's in the documentation. For example `var app = express();` is no longer like it. We're using const for everything in app.js
=> Updated README to reflect code examples correctly

app.js
I noticed deprecation warning below when I run test and app debugging console.
> (node:34180) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
To fix this warning I override mongoose's internal promise by node.js global promise function.
=> Fix Deprecation warning of mongoose.Promise 

app.js
If a user creates an account with an email address, then goes to `/account`, and links a social login page like Google+ at the bottom of the page, immediately after the  callback from Google+ the user will end up at `/` route (default) instead of /account since `req.session.returnTo` isn't set.
This pull request sets `req.session.returnTo` to `/account` if the request is already from an authenticated user and is from `/account` to have the user go back to the account page after a successful linking of a social login account.
=> Fix redirect issue in the account page

app.js
Adds a click-able link to the server address in the console (hold CMD on Mac, CTRL on Windows and click the link). Falls back to previous behaviour if the `env` is not set to `development`.
=> Adds link when developing locally on startup

app.js
Adapted fb request scope to match current scheme as previous one caused an error message (not all fields approved for app).
Properties requested are all covered by new definition: https://developers.facebook.com/docs/facebook-login/permissions/#reference-public_profile
Functionality is the same as before from what I can see.
Screenshot of error:
=> Adapted fb request scope to current definition

package.json
When deploying over an already-deployed app in heroku, binaries in the `vendor` directory of module `node-sass` disappear.
This extra post-installation step will force a fetch, for the application to start properly.
=> [fix] Heroku re-deploy issue with node-sass

controllers/api.js, controllers/user.js, package.json
Remove useless `async` package from `hackathon-starter` and replace it by built-in ES6 Promises, `then()` and `all()`, which are equivalent to `async::waterfall()` and `async::parallel()` use.
Side improvements: 
* `createRandomToken()` and `User.findOne(...)` are dispatched in parallel instead of sequentially (as happened before with `waterfall()`) because there is no dependency between each other;
* Suppresses the `async` idiomatic `if (err) { return done(err); }`, because "_If an error is thrown in the executor function, the promise is rejected._" (from [developer.mozilla.org Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise))
* Replaces the idiomatic `(err, results) => { if (err) { return next(err); } ... /* else block */` with …
=> Remove async package and use built-in ES6 Promises

config/passport.js
Line 108 now executes in ./config/passport.js: 
user.profile.gender = profile._json.gender;
and gender is stored in DB
=> add gender field to facebook strategy

README.md
On README.md, the section of [Obtaining API Keys](https://github.com/sahat/hackathon-starter#obtaining-api-keys) wasn't completely parsed well.
This commit separate paragraphs with line break after <img> tag.
Yes, check my Github repository which has the same README.md contents. you can find it fixed.
https://github.com/skatpgusskat/hackathon-starter#obtaining-api-keys
=> Fix unparsed markdown at README.md

docker-compose.yml
This was an example that could have been used to build / save dependencies (packages)
as separate image that would never need to be re-built. However, it is not needed or used currently.
=> Removing node_modules

controllers/api.js, controllers/user.js, package.json, test/models.js, yarn.lock
This commit:
- updates ESLint version to recent one
- configures ESLint to work with Node, Mocha and Jasmine syntax
- adds Chai assertion friendly plugin to work with
no-usunused-expressions configuration rule
- fixes linting erros in source code itself
- adds NPM task for lintin
=> :art: Fix ESLint configuration and source errors

views/api/twitter.pug
The URL for the API endpoints has been updated to a new working URL.
Images now working on the twitter feed.
=> Fixes dead URL in issue #726 and twitter image issue #728.

README.md
Removed following deprecated services:
- AlchemyAPI 
- Cognitive Commerce
- Cognitive Graph
- Cognitive Insights
- Document Conversion
- Retrieve and Rank
- Tradeoff Analytics
Added new service:
- Natural Language Understanding
Updated description of all services.
Added direct link to documentation for each service.
=> update list of Watson services

views/api/index.pug
Per the changelog from July 23, 2016, BitGo was removed due to a dependency issue
with `secp256k1` and Windows. This PR removes the reference on the `API Examples`
page template, addressing issue #725.
=> Cleaning up api/index view to remove reference to BitGo

controllers/api.js, views/api/lastfm.pug
Many of the URLs for images and links in the API Example for Last.fm
were incorrectly referenced, due to deprecations with attribute
interpolation syntax.
In addition, the order or promise resolution had mixed up the list
of top tracks and top albums, causing the same image to be shown for
all "top albums", and the list of "top tracks" were actually album
names. This has been corrected.
Addresses issue #770.
=> Fixing Pug template for Last.fm API Example

Dockerfile
In the current one, `COPY . /starter` comes before `npm install` -> which means every time source code changes, npm install will be executed again. 
So i have re-ordered the lines so that npm install can be **cached** and doesn't run every time (unless ofcourse package.json changes).
=> updated Dockerfile for better layers, caching

app.js
If you want to redirect to some url with queryParams after sign up/login, app only considers path. as we set the `req.path` to `req.session.returnTo`.
This will set `req.url` so path with queryParams will be set to `req.session.returnTo`
fixes #789
=> fix - returnTo with queryParams

.eslintrc
Adding env in eslint allows better code detection. For example `describe` is not underlined in red with this configuration because eslint detects that it is a unit test library.
Also, eslint always displayed `Definition for rule` chai-friendly/no-unused-expressions' was not found` because the plugin was not declared in.eslintrc.
=> better .eslintrc

.gitignore, package-lock.json, package.json
I set up a test coverage which allows to see which part of the code is not tested. Also after `npm test` the server was not closing, it is now the case.
I remove `--reporter spec` because `spec` is by default.
=> add coverage test and close server after test

views/api/foursquare.pug
I encountered a bug in foursquare view, the html page display 
`img(src='#{venueDetail.venue.photos.groups[0].items[0].prefix}150x150#{venueDetail.venue.photos.groups[0].items[0].suffix}')` 
instead of displaying an image.
=> fix bug display image in foursquare view

controllers/api.js, views/api/instagram.pug
The popular media must be removed because it has been deprecated since 2016 and this prevents the instagram api from working. According to the [documentation](https://elfsight.com/blog/2018/02/instagram-graph-api-changes/), the rest will be depreciated in 2020 because we used `Basic` to get the information.
partially fix #822
=> remove Popular images - instagram API

README.md
There were breaks between the transition from jade to pug (https://pugjs.org/api/migration-v2.html). Some of the links in the readme point to an old documentation or old converter. I've updated all this.
=> update README.md for the migration from jade to pug

package.json
node-sass is already declared in dependencies but it is also declared in PeerDependencies. It should be removed from PeerDependencies.
Also the version in peerDependencies has not been updated.
The library is even ignored when generating the package-lock.json file because it takes into account the last version declared in the dependencies.
I tested in local, travis build and heroku. It's working fine. 
In-part from #814
=> remove duplicate node-sass

README.md
It describes how to import and export with the es modules, but they are not supported by current versions of nodeJS. It's [experimental](https://nodejs.org/api/esm.html#esm_ecmascript_modules). You can use them with babel (or another transpilator), but it is not included in the project and will add a layer of complexity. I updated the readme with the currently supported native syntax.
=> update README.md with import/export supported by node

controllers/api.js
Remove `return` before `res.render`and `next`
=> standardize return

.travis.yml
It's no longer a nightly, show [blog](https://nodejs.org/en/blog/release/v10.0.0/)
=> Add nodeJS 10 in travis.yml

app.js
`mongoose.Promise = global.Promise` is useless with mongoose > 5 because it supports natively Promise.
=> remove mongoose global.Promise

views/partials/header.pug
Fixed a bug on the Home link's active class introduced by Bootstrap 4.
=> Fixed active class bug

app.js
Popper was incorrectly referencing the version in root ```dist/```, and throwing an error when used in ```layout.pug```.  This now correctly references the UMD version in ```dist/umd/```
=> Use Popper UMD

public/css/main.scss
The 5.1.0 to 5.1.1 Font-Awesome update changed the names of those files to drop the `fa-` prefix. More information at their [upgrading](https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md) guide.
=> Update main.scss w/correct fontawesome filenames

config/passport.js
Simple change to the doc comment for Twitter off. Noticed when I was digging through the repo.
=> Trivial doc comment format fix for Twitter auth

app.js, controllers/api.js, views/api/lastfm.pug
Fix for https://github.com/sahat/hackathon-starter/issues/854
- Added error handler middleware for when `NODE_ENV` is not equal to `development` that sends 500 response with generic `Server Error` message while logging the error to the server console. 
- In lastfm controller, added check for error code from the lastfm service with example of unique handling per code. Adjusted lastfm pug template to display the error message from the service when present and log to the server console. If no code present in error, pass along to generic error handler middleware.
=> fix #854: service error handling

public/css/main.scss, views/partials/header.pug
It collapses the navbar one breakpoint up (md > lg) fixing the alignment of the nav links, but to make this work properly, a Bootstrap 4 bug (https://github.com/twbs/bootstrap/issues/25654) needed to be addressed and this also solved the logo indentation.
As these are visually breaking issues in the current build, I tought it could be pulled separately from the other issues on #853 
Thanks!
=> Fix wrapping issues in the navbar and logo indentation

views/layout.pug
Per the [bootstrap documentation](https://getbootstrap.com/docs/4.0/components/popovers/):
> You must include popper.min.js before bootstrap.js or use bootstrap.bundle.min.js / bootstrap.bundle.js which contains Popper.js in order for popovers to work!
When popper is included _after_ bootstrap, the result is an error in the console when popper is initialized:
```
Uncaught TypeError: Bootstrap tooltips require Popper.js (https://popper.js.org)
at i (tooltip.js:117)
at new i (popover.js:11)
at HTMLButtonElement.<anonymous> (popover.js:158)
at Function.each (jquery.min.js:2)
at w.fn.init.each (jquery.min.js:2)
at w.fn.init.i._jQueryInterface [as popover] (popover.js:149)
at HTMLDocument.<anonymous> (main.js:6)
at l (jquery.min.js:2)
at c (jquery.min.js:2)
```
=> Re-order JS includes: Popper ahead of Bootstrap

README.md
The [issue referenced](https://github.com/sahat/hackathon-starter/issues/63#issuecomment-178876149) points to [the official deprecation notice of Mozilla Persona](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Persona).
Since the service was deprecated on November 30th, 2016, no new projects will be integrating it, so I think its safe to remove from the README.
=> Remove Mozilla Persona information from README

README.md
As discussed in #955 , the way to get connect string from Hosted MongoDB Atlas has been changed now.
The old text mentions 
> In the new screen, click on **Standard connection string (3.4+ driver)**. __*WARNING*__: Do not pick 3.6+ since there Express Session currently has a compatibility issue with it
The 3.4+/3.6+ driver options are no longer present in the interface. The text is getting updated for latest interface
=>  #955 Fix Hosted MongoDB Atlas instructions

config/passport.js, controllers/api.js, views/api/steam.pug
Updates the routes for:
I tried to keep the format of each route as consistent as I could. Each route has been manually tested with corresponding api keys.
Any feedback is welcome!
Done! 
Request is no longer a dependency.
Passport.js:
=> Refactored to use axios

README.md
Repository is moved to https://github.com/selectize/selectize.js by owner @brianreavis
=> Fixed selectize.js reference link

config/passport.js
Seems Google API changed its response and it is not possible to register a new user with google anymore. This small changes fixes the way to user's profile picture from the JSON data.
=> Fix for Google Oauth2 profile picture

views/account/profile.pug, views/account/reset.pug, views/account/signup.pug, views/contact.pug
Wherever that is possible to sync client HTML5 form validation with the
rules used on the server to validate user input, use type, min length
and required when applicable:
- add type=email, whenever email input is expected
- add minlength attribute, whenever input lenght is checked
- add required, whenever input is checked against empty values.
Thanks!
=> Use HTML5 native client form validation. Closes #1013

README.md
Hi,
I added `Click on "OAuth Apps"` in the GitHub API keys instruction, because otherwise, we may click on the "Register new application" under the `Github Apps` nav (the default one), which will be embarrassing ^^
=> Update GitHub API Keys instructions

public/css/themes/default/_default.scss, views/partials/header.pug
This corrects rendering the navbar using convention used by Bootswatch
and BS4, which usually either defaults to default styles for navbar or
uses combination of the navbar custom style and navbar custom baground
color (bg-*). IF `bg-*` is not present, this could lead to the
transparent background color for navbar when expanded.
The change contains a backward compatiblity fix for default theme, which
was done by not overriding `bg-*` value in navbars, but by using custom
background color as it was used before some changes in BS4. So by
default theme will use backward compatible override for background
color, not one that comes with the BS4 for 'bg-light' class.
The problems are discussed in comments here:
https://github.com/sahat/hackathon-starter/issues/853#issuecomment-475932533 …
=> Fix navbar rendering issues with theme support

public/css/main.scss, public/css/themes/default/_default.scss
This is the proposed way of fix issue with the custom `btn-raised` button variant 
being specific only to  the `default` theme in the project, which impacts rendering of the
content if other theme is being used.
This moves definition of the `.btn-raised` out of the `default` theme
definition into the main style project file, so it can be part of the
project style no matter what theme is applied to the project.
If users want to opt-out from that style, it's as easy now as replacing
the `btn-raised` type with e.g built-in one, like `btn-primary`.
The default state of the button tries to retain as much as possible
representation of the button under the default theme definition, while
also providing BS based variants for other states of the button like
active, focused, disabled, etc. …
=> Rework .btn-raised as BS custom button style. Fixes #1016

public/privacy-policy.html, public/terms-of-use.html, views/layout.pug, views/partials/footer.pug
**Notes**
fixes #1079 
- Using an [open source solution](https://github.com/osano/cookieconsent) for the cookie consent popup. The popup is just informational.
- Decided to go completely static for the privacy policy and terms of use pages since there's no dynamic content. (There is email address but its just a single place to update. Keeping it simple and fast)
=> Cookie consent, privacy policy and terms of use

views/partials/header.pug
Prevents the "You should not have pug tags with multiple attributes" error. 
It occurs due to code such as: 
a.nav-link(class=(title === 'Home') ? 'active' : '')(href='/') Home
on lines 50, 52 and 54 and affects any page that uses header.pug.
=> Change pug tags with multiple attributes

app.js
This merged caused logging issues and server errors due to mismatch number of parameters in methods such as logout.
Reverts sahat/hackathon-starter#1226
=> Revert "Updated error handler"

app.js
Renaming the browser-side cookie can reduce the chances of fingerprinting the tech stack (ExpressJS) by malicious parties. Setting secure attribute in the cookie configs will enable transfer of the cookie over SSL when an HTTPS connection is present.  CWE-614
=> Rename the cookie and set secure attribute

views/api/index.pug
Fixes #1270 
Some of the buttons did not have a sufficient contrast ratio as per the W3C Web Content Accessibility Guidelines (WCAG). This PR solves that by changing the text/background colours of some of these buttons (Stripe, Foursquare, Google Maps, HERE Maps) buttons under the `/api/examples` endpoint to ensure that these buttons have a **contrast ratio >= 7**.
1) **Stripe**:
- Text colour changed from **#fff** to **#000**
- Contrast ratio changes from **2.65** to **7.93**
2) **Foursquare**:
- Text colour changed from **#fff** to **#000**
- Contrast ratio changes from **2.50** to **8.39**
3) **Google Maps**:
- Text colour changed from **#fff** to **#000**
- Background colour changed from **#20a360** to **#20b067**
- Contrast ratio changes from **3.25** to **7.47** 
- Note: With the …
=> modify text/background colours for appropriate contrast ratios as per WCAG

Dockerfile, README.md, docker-compose.yml, package.json
Upgraded the docker-compose to version 3.8.
Upgrade the docker Node.js image to 20-slim.
Set mongo image to be the latest instead of a preset version that can go out of date often. Added the ability to set the docker environment as development or production. Added a check to the package.json prepare script to only install husky’s execution in non-production environments. This prevents npm install from failing in production environments, where dev dependencies may not be installed. Husky has been a dev dependency. Fixed a bug where docker-compose was overwriting the application/build folder causing removal of css files that were built with sass. Removed the extra end of line spaces in docker-compose.yml.
=> Limit husky to non-prod & Upgrade/Fix Docker

README.md
Updated Read Me with the new updated logo of twitter.
=> Update README.md with new twitter logo

Dockerfile
Each time a RUN instruction is added, a new layer is introduced into the final image.
This has a direct impact on build time and image size. Chaining commands into a single RUN statement using && will use a single layer, thus reducing the number of layers in the image.
Issue detected by SonarQube Cloud 
On dockerfile
=> Merging RUN instruction (reduced number of layers in image)

README.md, app.js, controllers/user.js, models/User.js, test/models.js, views/account/login.pug, views/account/signup.pug
- Add passwordless login option via email links
- Add passwordless signup option with automatic login link
- Refactor email verification system for unified security settings
- Add IP hash verification to prevent MITM and CSRF attacks
- Add token expiration and automatic cleanup via middleware
- Add database indexes for token fields
- Improve email templates with security instructions
- Enhance flash messages for better user feedback
- Add token verification checks before processing links
- Consolidate email sending logic for maintainability
- Add security advisory when emailing auth links
- Implement automatic cleanup of expired tokens on save
- Add more restrictive rate limiting to auth routes
- Add timing-safe token verification to harden against CWE-208
This major update improves …
=> feat: Implement passwordless authentication system

.env.example, README.md, controllers/contact.js, test/contact.js, views/contact.pug
Don't block developers if they don't have a reCAPTCHA key; notify them in the console to add one before going to production.
=> fix: Skip reCAPTCHA and a console warning if key is missing

test/e2e/lastfm.e2e.test.js
Add end-to-end tests for Last.fm API integration covering:
- Basic page structure and navigation
- API response handling (success/error cases)
- Data structure verification
- External link validation
- Graceful handling of missing data
=> test(e2e): add comprehensive Last.fm API integration tests

test/e2e/scraping.e2e.test.js
Fixes - #1429 
Added checks for -
- page basics
- table exists with headers
- num of links must be greater than 25
Screenshot of the console output -
Screenshot of webpage -
=> Add e2e tests for web scraping

test/e2e/openai-moderation.e2e.test.js
Fixes - #1431 
- Added 3 Playwright E2E tests for `/ai/openai-moderation` endpoint
- Tests cover: page load with error handling, harmful content flagging, and safe content validation
- Validates all UI elements: moderation result, category scores, flagged categories list [here](https://github.com/sahat/hackathon-starter/compare/master...Mrinank-Bhowmick:hackathon-starter:test/openai?expand=1#diff-38939d520f8969cf2e482cf8cd0352d5d8b6f1395df765ad758a0237bb30d55bR50)
Screenshot of the console output - 
screenshot of website
screenshot of playwright-report
=> test: add E2E tests for OpenAI Moderation API
